# Generated by Django 5.0.2 on 2025-03-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
